# Numpy

In [2]:
import numpy as np
a=np.array([1,2,3])
a
a.shape

(3,)

In [3]:
import numpy as np
a=np.array([[1,2,3],[5,4,3]])
print(a)
a.shape

[[1 2 3]
 [5 4 3]]


(2, 3)

In [4]:
import numpy as np
a=np.arange(0,9)
a
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
import numpy as np
import random as r
r=import random.randint(0,9)

In [15]:
import numpy as np
a=np.linspace(0,6,10)
a

array([0.        , 0.66666667, 1.33333333, 2.        , 2.66666667,
       3.33333333, 4.        , 4.66666667, 5.33333333, 6.        ])

In [19]:
import numpy as np
a=np.ones((3,4),int)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [7]:
y=np.array([4,5,6])
y

array([4, 5, 6])

In [10]:
[x.dot(y)]  

[32]

- Here dot is used as a  two matrices are taken that is take it as 1X2 != 1x2  ......     
- .dot is reverse one matrix 1x2 as 2x1 and 1x2  now 1 row and 1 colo is equal

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [12]:
a=np.random.randint(0,9,size=(3,2))
a
a.T



array([[8, 0, 1],
       [4, 6, 5]])

In [13]:
a

array([[8, 4],
       [0, 6],
       [1, 5]])

In [14]:
a.min()
a.max()
a.sum()

24

In [20]:
a=[2
  3
  4]

SyntaxError: invalid syntax (<ipython-input-20-774a32579246>, line 2)

In [ ]:
a=